In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def fitness_function(x):
    return x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2

In [ ]:
lower_bound =  -5
upper_bound =  5
num_iterations =  10
population_size =  5
tf = 2

In [ ]:
class TLBO:
  def __init__(self, fitness_function, lower_bound, upper_bound, num_iterations, population_size, tf):
    self.fitness_function = fitness_function
    self.lower_bound = lower_bound
    self.upper_bound = upper_bound
    self.num_iterations = num_iterations
    self.population_size = population_size
    self.tf = tf

  def tlbo(self):
    population = np.random.uniform(self.lower_bound, self.upper_bound, size=(self.population_size, 4))
    scores = np.array([self.fitness_function(individual) for individual in population])
    for iteration in range(self.num_iterations):
      print(f"positions in iteration {iteration}: {population}")
      print(f"Fitness Functions: {scores}")
      for i in range(self.population_size):
        # Teaching phase
        teacher_idx = np.argmin(scores)
        teacher = population[teacher_idx]
        print(f"Teacher: {teacher} and fitness function {scores[teacher_idx]} ")
        mean = np.mean(population, axis=0)
        print(f"Mean: {mean}")
        if i != teacher_idx:
          r = np.random.uniform(low=0, high=1,size = 4)
          new_x = population[i] + r * (teacher - self.tf*mean)
          new_x = np.clip(new_x, self.lower_bound, self.upper_bound)
          if self.fitness_function(new_x) < self.fitness_function(population[i]):
            population[i] = new_x
            scores[i] = self.fitness_function(new_x)
        print(f"positions after Teacher phase: {population}")
        #learner phase
        r = np.random.uniform(low=0, high=1,size = 4)
        random_row_index = np.random.randint(0, population.shape[0])
        Xp = population[random_row_index]
        print(f"Random Partner {Xp}")
        if self.fitness_function(population[i]) < self.fitness_function(Xp):
          new_x = population[i]+ r*(population[i] - Xp)
        else : new_x = population[i]- r*( Xp - population[i])
        new_x = np.clip(new_x, self.lower_bound, self.upper_bound)
        if self.fitness_function(new_x) < self.fitness_function(population[i]):
            population[i] = new_x
            scores[i] = self.fitness_function(new_x)
        print(f"positions after Learner phase: {population}")

tlbo = TLBO(fitness_function, lower_bound, upper_bound, num_iterations, population_size, tf)
tlbo.tlbo()


positions in iteration 0: [[-0.96288849  1.01754328 -3.6952415   4.99475851]
 [ 2.74437386  4.97137037  3.67009596  1.76169823]
 [ 0.15659063  1.89276377  1.15393645 -4.67175496]
 [-1.35710545 -4.44869024  3.55067631 -2.65600035]
 [-4.11300889 -2.32005864  4.49136492  2.23966002]]
Fitness Functions: [40.56497093 48.81929621 26.76393908 41.2942202  47.48795008]
Teacher: [ 0.15659063  1.89276377  1.15393645 -4.67175496] and fitness function 26.763939077861757 
Mean: [-0.70640767  0.22258571  1.83416643  0.33367229]
positions after Teacher phase: [[-0.50790137  1.83077973 -3.79240949  3.59774514]
 [ 2.74437386  4.97137037  3.67009596  1.76169823]
 [ 0.15659063  1.89276377  1.15393645 -4.67175496]
 [-1.35710545 -4.44869024  3.55067631 -2.65600035]
 [-4.11300889 -2.32005864  4.49136492  2.23966002]]
Random Partner [-0.50790137  1.83077973 -3.79240949  3.59774514]
positions after Learner phase: [[-0.50790137  1.83077973 -3.79240949  3.59774514]
 [ 2.74437386  4.97137037  3.67009596  1.761698